apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
spec:
  replicas: 3  # Change this as needed
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      serviceAccountName: jenkins
      containers:
        - name: dashboard
          image: frawatson/dashboard:latest  # Replace <CONTAINER_REGISTRY> with your registry details
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-service
spec:
  selector:
    app: dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Use "LoadBalancer" for cloud providers like AWS or GCP; use "NodePort" for local Kubernetes clusters
